# PUT YOUR GITHUB ACTION WORKFLOW HERE

name: Basic GitHub Action

on: workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-latest      
    steps:
      - name: Hello world
        run: echo "Hello World"
        
